# This file was generated by GoReleaser. DO NOT EDIT.
cask "axiom" do
  version "0.35.18"

  on_macos do
    on_arm do
      sha256 "e6478d9d3260343fbfc2558bf30d049f2cbe7bc287c4f5d32e4f7825843d01ce"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "365408ddfe5fbbef8f46c611c06eab2483656851387884bcf349a5333fba4c5a"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59ad2d04280bd435ef024c1c21f6f4542f94bee4e1e34adc871dd5f0cd9be535"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "81b9aba138ae7354732b7fab0b15fef476931ee7cb41392395d851ab505a62dd"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "axiom"
  desc "Axiom CLI — build, run, and publish node packages"
  homepage "https://axiomide.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axiom"

  # No zap stanza required
end
