# This file was generated by GoReleaser. DO NOT EDIT.
cask "axiom" do
  version "0.33.4"

  on_macos do
    on_intel do
      sha256 "13219e3eded713097c934d768c4811d1f5cb442b53086140d7087c21a6df1e84"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67661e153ecd005c1ab742cebe99b6d391b31ac1c9f37ffd09d348cd64857a83"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2deccef89fa522f9cfefb138ce0475b359e5ddff72d9f884aedcd24418c288f5"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "081dda94cc6e884117aacd1d151ea81094bcd662f8ad7c3787e690eb81eb390a"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_arm64.tar.gz"
    end
  end

  name "axiom"
  desc "Axiom CLI — build, run, and publish node packages"
  homepage "https://axiomide.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axiom"

  # No zap stanza required

end
