# This file was generated by GoReleaser. DO NOT EDIT.
cask "axiom" do
  version "0.41.11"

  on_macos do
    on_arm do
      sha256 "2a5480c61e0f184dfd9a01e42563664d30e3856e753522a5ac77167afd644e80"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bc249fc658fe18df32d6d1c29f1b5fc714581d3f186b89a1f255ccee70ae5daf"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "82c9d2dd990fc84fd9cfb823bb9f5e218dad50e3ab5b39681c48126a9f10f69d"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5da6cc7f7db541c91fb621dd43400710f9d4184fa72ac716d3fd8e40632d6be6"
      url "https://github.com/AxiomIDE/axiom-releases/releases/download/v#{version}/axiom_#{version}_linux_amd64.tar.gz"
    end
  end

  name "axiom"
  desc "Axiom CLI — build, run, and publish node packages"
  homepage "https://axiomide.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "axiom"

  # No zap stanza required
end
